# https://github.com/linuxsoftware/ls.sampleproject

language: python

env:
 - WAGTAIL_VERSION=2.2.2
 - WAGTAIL_VERSION=2.3
 - WAGTAIL_VERSION=2.4

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required

install:
  - pip install -r requirements.txt
  - pip install wagtail==$WAGTAIL_VERSION

script:
  - ./runtests.py --coverage

after_success:
  - coveralls
