# https://github.com/linuxsoftware/ls.sampleproject

language: python

python:
  - "3.5"

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - python ./runtests.py --coverage

after_success:
  - coveralls
